version: '3.8'

services:
  # 1. سرویس بک‌‌اند (Django)
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    # متغیرهای محیطی مخصوص داکر
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # 2. سرویس دیتابیس (Postgres)
  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tasktracker_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret

  # 3. سرویس ردیس (Redis) - جدید
  redis:
    image: redis:7-alpine
    restart: always

  # 4. سرویس سلری ورکر (Celery Worker) - جدید
  celery_worker:
    build: .
 
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

 
  celery_beat:
    build: .
  
    command: celery -A config beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # 6. سرویس ایمیل تستی (Mailpit)
  mailpit:
    image: axllent/mailpit
    container_name: tasktracker_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

volumes:
  pg_data:
